language: node_js
addons:
  apt:
    update: true
before_install:
- npm install nw-builder --save-dev
- npm install compressing --save-dev
- npm install os-tmpdir -g
install: git branch
node_js:
- '11'
branches:
  include:
  - gh-pages
script: node ./s-build-all.js --production
deploy:
  provider: releases
  api_key:
    secure: CBSXvp0SLniuVce95oeOjrYYKXzR/LB01GutCM8xyrG8526u27T0OX0j6fiMDR6BzbUaEhD6MfvKhDgx3gXreenfpvtUn+4M9PAsMxx/cpU3M8rTq1cfGSl3V1xpLnII3L76feiJ1QxCZ+yyR8ddV1blEFMk5MNwEGeL8g2wcCpNC5NL+jUd88ttwuPueCwD28Ytdof3PcOaM6zTjNg3WSbcqqS42voLDOGMD+XBPU45JcJl59ZVdInTr3Ejykfxon8YqGwT7miOKwnVisBh926IyLe6dlAsgwSn+is6CyhoLiXN4O/aPbbwfv25dubJYYLgEXiIA7Zutja8/AY9hDkYp6Pa2sipMB+dc5+9xPR9v1STGRwl/uw26GYBl6Fo/0Is49QfdK9D2emnpwFwvAYDzDRnuiinXUSPRKdSUM0zS7nsMt76QOGTg9Hf47zZmBt0MaoxlTyebahFKHqJXUH9zsKvr978AryAf+W++32PHnvhDlsrqhNuqOQfxGH0KXiAKYtnGZk6PDrESxiejwdpvxDJ28Zci/3mEcJ0LnRZ40jZPhH68z01xQ3SG5XPlhQS89DrLIrU0cXil5UfK2+w5GQFaiyK4q1NcD3CiqAiFjFVnTWfiXjgxTpaRHtuOkfPRXjiX8ZcZgyAKnw+mNGbNQUTwHqTZ688knxH2AU=
  file: build/*.zip
  file_glob: true
  skip_cleanup: true
  on:
    all_branches: true
    tags: true

notifications:
  email:
    - 15816141883@163.com
